<?php

function fail(string $message): never {
    fwrite(STDERR, "ERROR: {$message}\n");
    exit(1);
}

function writeFileUtf8(string $path, string $content): void {
    if (file_put_contents($path, $content) === false) {
        fail("No se pudo guardar {$path}");
    }
}

$root = dirname(__DIR__);

/*
|--------------------------------------------------------------------------
| Rutas
|--------------------------------------------------------------------------
*/
$routesPath = $root.'/routes/comercio.php';
$routes = file_get_contents($routesPath);

if ($routes === false) {
    fail('No se pudo leer routes/comercio.php');
}

if (! str_contains($routes, 'CommerceCatalogController')) {
    $routes = str_replace(
        "use App\\Http\\Controllers\\Comercio\\CommerceBrandingController;",
        "use App\\Http\\Controllers\\Comercio\\CommerceBrandingController;\nuse App\\Http\\Controllers\\Comercio\\CommerceCatalogController;",
        $routes
    );
}

if (! str_contains($routes, "catalog.products.store")) {
    $anchor = "            Route::post(\n                '/branding',";

    $block = <<<'PHP'

            /*
            |--------------------------------------------------------------------------
            | Catálogos
            |--------------------------------------------------------------------------
            */

            Route::post(
                '/catalogos/categorias',
                [CommerceCatalogController::class, 'storeCategory']
            )->name('catalog.categories.store');

            Route::post(
                '/catalogos/marcas',
                [CommerceCatalogController::class, 'storeBrand']
            )->name('catalog.brands.store');

            Route::post(
                '/catalogos/productos',
                [CommerceCatalogController::class, 'storeProduct']
            )->name('catalog.products.store');

            Route::put(
                '/catalogos/productos/{product}',
                [CommerceCatalogController::class, 'updateProduct']
            )->name('catalog.products.update');

            Route::patch(
                '/catalogos/productos/{product}/visibilidad',
                [CommerceCatalogController::class, 'toggleVisibility']
            )->name('catalog.products.visibility');

            Route::delete(
                '/catalogos/productos/{product}',
                [CommerceCatalogController::class, 'destroyProduct']
            )->name('catalog.products.destroy');

PHP;

    $position = strpos($routes, $anchor);

    if ($position === false) {
        fail('No se encontro el punto para insertar rutas de catalogos');
    }

    $routes = substr($routes, 0, $position).$block.substr($routes, $position);
}

writeFileUtf8($routesPath, $routes);

/*
|--------------------------------------------------------------------------
| CommerceUser
|--------------------------------------------------------------------------
*/
$userPath = $root.'/app/Models/Comercio/CommerceUser.php';
$user = file_get_contents($userPath);

if ($user === false) {
    fail('No se pudo leer CommerceUser.php');
}

if (! str_contains($user, 'catalogProducts(): HasMany')) {
    $method = <<<'PHP'

    public function catalogCategories(): HasMany
    {
        return $this->hasMany(
            CommerceCatalogCategory::class,
            'commerce_user_id'
        );
    }

    public function catalogBrands(): HasMany
    {
        return $this->hasMany(
            CommerceCatalogBrand::class,
            'commerce_user_id'
        );
    }

    public function catalogProducts(): HasMany
    {
        return $this->hasMany(
            CommerceCatalogProduct::class,
            'commerce_user_id'
        );
    }
PHP;

    $lastBrace = strrpos($user, '}');

    if ($lastBrace === false) {
        fail('No se encontro el cierre de CommerceUser');
    }

    $user = substr($user, 0, $lastBrace).$method."\n}\n";
}

writeFileUtf8($userPath, $user);

/*
|--------------------------------------------------------------------------
| DashboardController
|--------------------------------------------------------------------------
*/
$controllerPath = $root.'/app/Http/Controllers/Comercio/DashboardController.php';
$controller = file_get_contents($controllerPath);

if ($controller === false) {
    fail('No se pudo leer DashboardController.php');
}

foreach ([
    'CommerceCatalogCategory',
    'CommerceCatalogBrand',
    'CommerceCatalogProduct',
] as $model) {
    $use = "use App\\Models\\Comercio\\{$model};";

    if (! str_contains($controller, $use)) {
        $controller = str_replace(
            "use App\\Models\\Comercio\\CommerceBranding;",
            "use App\\Models\\Comercio\\CommerceBranding;\n{$use}",
            $controller
        );
    }
}

if (! str_contains($controller, '$catalogCategories =')) {
    $anchor = <<<'PHP'
        $branding = CommerceBranding::query()
            ->where('commerce_user_id', $comercio->id)
            ->first();
PHP;

    $queries = $anchor.<<<'PHP'


        $catalogCategories = CommerceCatalogCategory::query()
            ->where('commerce_user_id', $comercio->id)
            ->orderBy('sort_order')
            ->orderBy('name')
            ->get();

        $catalogBrands = CommerceCatalogBrand::query()
            ->where('commerce_user_id', $comercio->id)
            ->orderBy('name')
            ->get();

        $catalogProducts = CommerceCatalogProduct::query()
            ->with([
                'category',
                'brand',
                'variants',
                'stocks.branch',
            ])
            ->where('commerce_user_id', $comercio->id)
            ->latest('id')
            ->get();
PHP;

    if (! str_contains($controller, $anchor)) {
        fail('No se encontro la consulta de branding en DashboardController');
    }

    $controller = str_replace($anchor, $queries, $controller);
}

$controller = str_replace(
    "            'branding',\n",
    "            'branding',\n            'catalogos',\n",
    $controller
);

if (! str_contains($controller, "'catalogCategories' =>")) {
    $controller = str_replace(
        "            'branding' => \$branding,\n",
        "            'branding' => \$branding,\n            'catalogCategories' => \$catalogCategories,\n            'catalogBrands' => \$catalogBrands,\n            'catalogProducts' => \$catalogProducts,\n",
        $controller
    );
}

writeFileUtf8($controllerPath, $controller);

/*
|--------------------------------------------------------------------------
| Dashboard Blade
|--------------------------------------------------------------------------
*/
$dashboardPath = $root.'/resources/views/comercio/dashboard.blade.php';
$dashboard = file_get_contents($dashboardPath);

if ($dashboard === false) {
    fail('No se pudo leer dashboard.blade.php');
}

$oldButton = <<<'BLADE'
            <button type="button" class="commerce-admin__tab" disabled>
                Catálogos
            </button>
BLADE;

$newButton = <<<'BLADE'
            <button
                type="button"
                class="commerce-admin__tab {{ ($activeTab ?? 'usuarios') === 'catalogos' ? 'is-active' : '' }}"
                data-commerce-tab-button="catalogos"
                aria-pressed="{{ ($activeTab ?? 'usuarios') === 'catalogos' ? 'true' : 'false' }}"
            >
                Catálogos
            </button>
BLADE;

if (str_contains($dashboard, $oldButton)) {
    $dashboard = str_replace($oldButton, $newButton, $dashboard);
}

if (! str_contains($dashboard, 'data-commerce-tab-panel="catalogos"')) {
    $brandingMarker = 'data-commerce-tab-panel="branding"';
    $markerPosition = strpos($dashboard, $brandingMarker);

    if ($markerPosition === false) {
        fail('No se encontro el panel Branding para insertar Catalogos');
    }

    $panelStart = strrpos(substr($dashboard, 0, $markerPosition), '<div');

    if ($panelStart === false) {
        fail('No se encontro el inicio del panel Branding');
    }

    $panel = base64_decode('ICAgICAgICA8ZGl2CiAgICAgICAgICAgIGNsYXNzPSJjb21tZXJjZS10YWItcGFuZWwge3sgKCRhY3RpdmVUYWIgPz8gJ3VzdWFyaW9zJykgPT09ICdjYXRhbG9nb3MnID8gJ2lzLWFjdGl2ZScgOiAnJyB9fSIKICAgICAgICAgICAgZGF0YS1jb21tZXJjZS10YWItcGFuZWw9ImNhdGFsb2dvcyIKICAgICAgICA+CiAgICAgICAgICAgIEBwaHAKICAgICAgICAgICAgICAgICRjYXRhbG9nQ2F0ZWdvcmllc0NvbGxlY3Rpb24gPSBjb2xsZWN0KCRjYXRhbG9nQ2F0ZWdvcmllcyA/PyBbXSk7CiAgICAgICAgICAgICAgICAkY2F0YWxvZ0JyYW5kc0NvbGxlY3Rpb24gPSBjb2xsZWN0KCRjYXRhbG9nQnJhbmRzID8/IFtdKTsKICAgICAgICAgICAgICAgICRjYXRhbG9nUHJvZHVjdHNDb2xsZWN0aW9uID0gY29sbGVjdCgkY2F0YWxvZ1Byb2R1Y3RzID8/IFtdKTsKICAgICAgICAgICAgICAgICRjYXRhbG9nQnJhbmNoZXNDb2xsZWN0aW9uID0gY29sbGVjdCgkYnJhbmNoZXMgPz8gW10pOwoKICAgICAgICAgICAgICAgICRjYXRhbG9nVmlzaWJsZUNvdW50ID0gJGNhdGFsb2dQcm9kdWN0c0NvbGxlY3Rpb24tPndoZXJlKCdpc192aXNpYmxlJywgdHJ1ZSktPmNvdW50KCk7CiAgICAgICAgICAgICAgICAkY2F0YWxvZ0FjdGl2ZUNvdW50ID0gJGNhdGFsb2dQcm9kdWN0c0NvbGxlY3Rpb24tPndoZXJlKCdzdGF0dXMnLCAnYWN0aXZlJyktPmNvdW50KCk7CiAgICAgICAgICAgICAgICAkY2F0YWxvZ0xvd1N0b2NrQ291bnQgPSAkY2F0YWxvZ1Byb2R1Y3RzQ29sbGVjdGlvbi0+ZmlsdGVyKGZ1bmN0aW9uICgkcHJvZHVjdCkgewogICAgICAgICAgICAgICAgICAgIHJldHVybiBjb2xsZWN0KCRwcm9kdWN0LT5zdG9ja3MgPz8gW10pLT5jb250YWlucyhmdW5jdGlvbiAoJHN0b2NrKSB7CiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiAoZmxvYXQpICRzdG9jay0+c3RvY2sgPD0gKGZsb2F0KSAkc3RvY2stPm1pbmltdW1fc3RvY2s7CiAgICAgICAgICAgICAgICAgICAgfSk7CiAgICAgICAgICAgICAgICB9KS0+Y291bnQoKTsKICAgICAgICAgICAgQGVuZHBocAoKICAgICAgICAgICAgPHNlY3Rpb24gY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2ciPgogICAgICAgICAgICAgICAgPGhlYWRlciBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19faGVhZGVyIj4KICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICA8aDI+Q2F0w6Fsb2dvczwvaDI+CiAgICAgICAgICAgICAgICAgICAgICAgIDxwPkFkbWluaXN0cmEgY2F0ZWdvcsOtYXMsIG1hcmNhcywgcHJvZHVjdG9zLCB2YXJpYW50ZXMsIHByZWNpb3MgZSBpbnZlbnRhcmlvIHBvciBzdWN1cnNhbC48L3A+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2hlYWRlcj4KCiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19rcGlzIj4KICAgICAgICAgICAgICAgICAgICA8YXJ0aWNsZSBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fa3BpIj4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+UHJvZHVjdG9zIHkgc2VydmljaW9zPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Ryb25nPnt7ICRjYXRhbG9nUHJvZHVjdHNDb2xsZWN0aW9uLT5jb3VudCgpIH19PC9zdHJvbmc+CiAgICAgICAgICAgICAgICAgICAgPC9hcnRpY2xlPgoKICAgICAgICAgICAgICAgICAgICA8YXJ0aWNsZSBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fa3BpIj4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+QWN0aXZvczwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgPHN0cm9uZz57eyAkY2F0YWxvZ0FjdGl2ZUNvdW50IH19PC9zdHJvbmc+CiAgICAgICAgICAgICAgICAgICAgPC9hcnRpY2xlPgoKICAgICAgICAgICAgICAgICAgICA8YXJ0aWNsZSBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fa3BpIj4KICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+VmlzaWJsZXM8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgIDxzdHJvbmc+e3sgJGNhdGFsb2dWaXNpYmxlQ291bnQgfX08L3N0cm9uZz4KICAgICAgICAgICAgICAgICAgICA8L2FydGljbGU+CgogICAgICAgICAgICAgICAgICAgIDxhcnRpY2xlIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19rcGkiPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5TdG9jayBiYWpvPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICA8c3Ryb25nPnt7ICRjYXRhbG9nTG93U3RvY2tDb3VudCB9fTwvc3Ryb25nPgogICAgICAgICAgICAgICAgICAgIDwvYXJ0aWNsZT4KICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgICAgIDxzZWN0aW9uIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19ibG9jayI+CiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fYmxvY2staGVhZCI+CiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aDM+Q2F0ZWdvcsOtYXMgeSBtYXJjYXM8L2gzPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHA+T3JnYW5pemEgZWwgY2F0w6Fsb2dvIGFudGVzIGRlIGNyZWFyIHByb2R1Y3Rvcy48L3A+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19taW5pLWdyaWQiPgogICAgICAgICAgICAgICAgICAgICAgICA8Zm9ybSBtZXRob2Q9IlBPU1QiIGFjdGlvbj0ie3sgcm91dGUoJ2NvbWVyY2lvLmNhdGFsb2cuY2F0ZWdvcmllcy5zdG9yZScpIH19Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBjc3JmCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5OdWV2YSBjYXRlZ29yw61hPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJuYW1lIiBwbGFjZWhvbGRlcj0iRWouIEFsaW1lbnRvIHNlY28iIHJlcXVpcmVkPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJoaWRkZW4iIG5hbWU9ImlzX2FjdGl2ZSIgdmFsdWU9IjEiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiB0eXBlPSJzdWJtaXQiIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19idXR0b24gY29tbWVyY2UtY2F0YWxvZ19fYnV0dG9uLS1zb2Z0Ij5BZ3JlZ2FyIGNhdGVnb3LDrWE8L2J1dHRvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPC9mb3JtPgoKICAgICAgICAgICAgICAgICAgICAgICAgPGZvcm0gbWV0aG9kPSJQT1NUIiBhY3Rpb249Int7IHJvdXRlKCdjb21lcmNpby5jYXRhbG9nLmJyYW5kcy5zdG9yZScpIH19Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBjc3JmCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5OdWV2YSBtYXJjYTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0idGV4dCIgbmFtZT0ibmFtZSIgcGxhY2Vob2xkZXI9IkVqLiBQZXQgTnV0cml0aW9uIiByZXF1aXJlZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0iaGlkZGVuIiBuYW1lPSJpc19hY3RpdmUiIHZhbHVlPSIxIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxidXR0b24gdHlwZT0ic3VibWl0IiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fYnV0dG9uIGNvbW1lcmNlLWNhdGFsb2dfX2J1dHRvbi0tc29mdCI+QWdyZWdhciBtYXJjYTwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgICAgICA8L2Zvcm0+CgogICAgICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImRpc3BsYXk6YmxvY2s7Y29sb3I6IzY0NzQ4Yjtmb250LXNpemU6MTFweDtmb250LXdlaWdodDo5MDA7bWFyZ2luLWJvdHRvbTo2cHg7Ij5SZXN1bWVuPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHN0cm9uZyBzdHlsZT0iZm9udC1zaXplOjIwcHg7Y29sb3I6IzExMTgyNzsiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHt7ICRjYXRhbG9nQ2F0ZWdvcmllc0NvbGxlY3Rpb24tPmNvdW50KCkgKyAkY2F0YWxvZ0JyYW5kc0NvbGxlY3Rpb24tPmNvdW50KCkgfX0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvc3Ryb25nPgogICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fdGFncyI+CiAgICAgICAgICAgICAgICAgICAgICAgIEBmb3JlYWNoICgkY2F0YWxvZ0NhdGVnb3JpZXNDb2xsZWN0aW9uIGFzICRjYXRlZ29yeSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX190YWciPkNhdGVnb3LDrWEgwrcge3sgJGNhdGVnb3J5LT5uYW1lIH19PC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICBAZW5kZm9yZWFjaAoKICAgICAgICAgICAgICAgICAgICAgICAgQGZvcmVhY2ggKCRjYXRhbG9nQnJhbmRzQ29sbGVjdGlvbiBhcyAkYnJhbmQpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fdGFnIj5NYXJjYSDCtyB7eyAkYnJhbmQtPm5hbWUgfX08L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgIEBlbmRmb3JlYWNoCiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L3NlY3Rpb24+CgogICAgICAgICAgICAgICAgPHNlY3Rpb24gY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2Jsb2NrIj4KICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19ibG9jay1oZWFkIj4KICAgICAgICAgICAgICAgICAgICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxoMz5BbHRhIGRlIHByb2R1Y3RvIG8gc2VydmljaW88L2gzPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHA+Q2FwdHVyYSBpbmZvcm1hY2nDs24gY29tZXJjaWFsLCB2YXJpYW50ZSBiw6FzaWNhIHkgc3RvY2sgcG9yIHN1Y3Vyc2FsLjwvcD4KICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgICAgICAgIDxmb3JtCiAgICAgICAgICAgICAgICAgICAgICAgIGlkPSJjb21tZXJjZUNhdGFsb2dQcm9kdWN0Rm9ybSIKICAgICAgICAgICAgICAgICAgICAgICAgbWV0aG9kPSJQT1NUIgogICAgICAgICAgICAgICAgICAgICAgICBhY3Rpb249Int7IHJvdXRlKCdjb21lcmNpby5jYXRhbG9nLnByb2R1Y3RzLnN0b3JlJykgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtc3RvcmUtYWN0aW9uPSJ7eyByb3V0ZSgnY29tZXJjaW8uY2F0YWxvZy5wcm9kdWN0cy5zdG9yZScpIH19IgogICAgICAgICAgICAgICAgICAgICAgICBlbmN0eXBlPSJtdWx0aXBhcnQvZm9ybS1kYXRhIgogICAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgICAgICAgQGNzcmYKICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9ImhpZGRlbiIgbmFtZT0iX21ldGhvZCIgaWQ9ImNvbW1lcmNlQ2F0YWxvZ01ldGhvZCIgdmFsdWU9IlBPU1QiPgoKICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZm9ybS1ncmlkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPlRpcG88L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNlbGVjdCBuYW1lPSJpdGVtX3R5cGUiIHJlcXVpcmVkPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJwcm9kdWN0Ij5Qcm9kdWN0bzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJzZXJ2aWNlIj5TZXJ2aWNpbzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvc2VsZWN0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5Ob21icmU8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIG5hbWU9Im5hbWUiIHJlcXVpcmVkPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5TS1U8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIG5hbWU9InNrdSIgcmVxdWlyZWQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPkPDs2RpZ28gZGUgYmFycmFzPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJiYXJjb2RlIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+Q2F0ZWdvcsOtYTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c2VsZWN0IG5hbWU9ImNhdGVnb3J5X2lkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iIj5TaW4gY2F0ZWdvcsOtYTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAZm9yZWFjaCAoJGNhdGFsb2dDYXRlZ29yaWVzQ29sbGVjdGlvbiBhcyAkY2F0ZWdvcnkpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJ7eyAkY2F0ZWdvcnktPmlkIH19Ij57eyAkY2F0ZWdvcnktPm5hbWUgfX08L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQGVuZGZvcmVhY2gKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+TWFyY2E8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNlbGVjdCBuYW1lPSJicmFuZF9pZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+U2luIG1hcmNhPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBmb3JlYWNoICgkY2F0YWxvZ0JyYW5kc0NvbGxlY3Rpb24gYXMgJGJyYW5kKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0ie3sgJGJyYW5kLT5pZCB9fSI+e3sgJGJyYW5kLT5uYW1lIH19PC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBlbmRmb3JlYWNoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPlByZWNpbzwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0ibnVtYmVyIiBuYW1lPSJwcmljZSIgbWluPSIwIiBzdGVwPSIwLjAxIiB2YWx1ZT0iMCIgcmVxdWlyZWQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPlByZWNpbyBvZmVydGE8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9Im51bWJlciIgbmFtZT0ic2FsZV9wcmljZSIgbWluPSIwIiBzdGVwPSIwLjAxIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+VW5pZGFkPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzZWxlY3QgbmFtZT0idW5pdCIgcmVxdWlyZWQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9InBpZXphIj5QaWV6YTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJrZyI+S2lsb2dyYW1vPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9ImciPkdyYW1vPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9ImxpdHJvIj5MaXRybzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJzZXJ2aWNpbyI+U2VydmljaW88L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+RXN0YXR1czwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c2VsZWN0IG5hbWU9InN0YXR1cyIgcmVxdWlyZWQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9ImRyYWZ0Ij5Cb3JyYWRvcjwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJhY3RpdmUiPkFjdGl2bzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJpbmFjdGl2ZSI+SW5hY3Rpdm88L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+SW1hZ2VuPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJmaWxlIiBuYW1lPSJpbWFnZSIgYWNjZXB0PSIucG5nLC5qcGcsLmpwZWcsLndlYnAiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fY2hlY2siPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0iY2hlY2tib3giIG5hbWU9InRyYWNrX3N0b2NrIiB2YWx1ZT0iMSIgY2hlY2tlZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQ29udHJvbGFyIHN0b2NrCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2NoZWNrIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94IiBuYW1lPSJpc192aXNpYmxlIiB2YWx1ZT0iMSIgY2hlY2tlZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgVmlzaWJsZSBhbCBjbGllbnRlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2Zvcm0tZ3JpZCBjb21tZXJjZS1jYXRhbG9nX19mb3JtLWdyaWQtLXdpZGUiIHN0eWxlPSJtYXJnaW4tdG9wOjEycHg7Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPkRlc2NyaXBjacOzbiBjb3J0YTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGV4dGFyZWEgbmFtZT0ic2hvcnRfZGVzY3JpcHRpb24iPjwvdGV4dGFyZWE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPkRlc2NyaXBjacOzbiBjb21wbGV0YTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGV4dGFyZWEgbmFtZT0iZGVzY3JpcHRpb24iPjwvdGV4dGFyZWE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgogICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICAgICAgICAgIDxmaWVsZHNldCBzdHlsZT0ibWFyZ2luLXRvcDoxNHB4O2JvcmRlcjoxcHggZGFzaGVkIHJnYmEoMTUsMjMsNDIsLjE2KTtib3JkZXItcmFkaXVzOjE2cHg7cGFkZGluZzoxNHB4OyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGVnZW5kIHN0eWxlPSJwYWRkaW5nOjAgOHB4O2NvbG9yOiMzMzQxNTU7Zm9udC1zaXplOjEycHg7Zm9udC13ZWlnaHQ6OTAwOyI+VmFyaWFudGUgYsOhc2ljYSBvcGNpb25hbDwvbGVnZW5kPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2Zvcm0tZ3JpZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPk5vbWJyZSB2YXJpYW50ZTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIG5hbWU9InZhcmlhbnRfbmFtZSIgcGxhY2Vob2xkZXI9IkVqLiBCb2xzYSA1IGtnIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+U0tVIHZhcmlhbnRlPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0idGV4dCIgbmFtZT0idmFyaWFudF9za3UiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5BdHJpYnV0b3M8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJ2YXJpYW50X2F0dHJpYnV0ZXMiIHBsYWNlaG9sZGVyPSI1IGtnLCBhZHVsdG8sIHBvbGxvIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+UHJlY2lvIHZhcmlhbnRlPC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0ibnVtYmVyIiBuYW1lPSJ2YXJpYW50X3ByaWNlIiBtaW49IjAiIHN0ZXA9IjAuMDEiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgPC9maWVsZHNldD4KCiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX3N0b2NrLWdyaWQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgQGZvcmVsc2UgKCRjYXRhbG9nQnJhbmNoZXNDb2xsZWN0aW9uIGFzICRicmFuY2gpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fc3RvY2stcm93Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHN0cm9uZz57eyAkYnJhbmNoLT5icmFuY2hfbmFtZSB9fTwvc3Ryb25nPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19maWVsZCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5TdG9jazwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJudW1iZXIiIG5hbWU9ImJyYW5jaF9zdG9ja1t7eyAkYnJhbmNoLT5pZCB9fV0iIG1pbj0iMCIgc3RlcD0iMC4wMDEiIHZhbHVlPSIwIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+TcOtbmltbzwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJudW1iZXIiIG5hbWU9ImJyYW5jaF9taW5pbXVtX3N0b2NrW3t7ICRicmFuY2gtPmlkIH19XSIgbWluPSIwIiBzdGVwPSIwLjAwMSIgdmFsdWU9IjAiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19jaGVjayI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0iY2hlY2tib3giIG5hbWU9ImJyYW5jaF9hdmFpbGFibGVbe3sgJGJyYW5jaC0+aWQgfX1dIiB2YWx1ZT0iMSIgY2hlY2tlZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIERpc3BvbmlibGUKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBlbXB0eQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2VtcHR5Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgUmVnaXN0cmEgdW5hIHN1Y3Vyc2FsIHBhcmEgY29udHJvbGFyIGludmVudGFyaW8gcG9yIHViaWNhY2nDs24uCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBAZW5kZm9yZWxzZQogICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9ImRpc3BsYXk6ZmxleDtqdXN0aWZ5LWNvbnRlbnQ6ZmxleC1lbmQ7Z2FwOjEwcHg7bWFyZ2luLXRvcDoxNHB4OyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgaWQ9ImNvbW1lcmNlQ2F0YWxvZ1Jlc2V0QnV0dG9uIiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fYnV0dG9uIGNvbW1lcmNlLWNhdGFsb2dfX2J1dHRvbi0tc29mdCIgaGlkZGVuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIENhbmNlbGFyIGVkaWNpw7NuCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIHR5cGU9InN1Ym1pdCIgaWQ9ImNvbW1lcmNlQ2F0YWxvZ1N1Ym1pdEJ1dHRvbiIgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2J1dHRvbiI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgR3VhcmRhciBwcm9kdWN0bwogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgIDwvZm9ybT4KICAgICAgICAgICAgICAgIDwvc2VjdGlvbj4KCiAgICAgICAgICAgICAgICA8c2VjdGlvbiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fYmxvY2siPgogICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2Jsb2NrLWhlYWQiPgogICAgICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGgzPlByb2R1Y3RvcyByZWdpc3RyYWRvczwvaDM+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cD5CdXNjYSwgZmlsdHJhIHkgYWRtaW5pc3RyYSBlbCBjYXTDoWxvZ28gcHVibGljYWRvLjwvcD4KICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX3Rvb2xiYXIiPgogICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPkJ1c2Nhcjwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJzZWFyY2giIGlkPSJjb21tZXJjZUNhdGFsb2dTZWFyY2giIHBsYWNlaG9sZGVyPSJOb21icmUsIFNLVSwgbWFyY2EgbyBjYXRlZ29yw61hIj4KICAgICAgICAgICAgICAgICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICAgICAgICAgICAgICAgIDxsYWJlbCBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZmllbGQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+Q2F0ZWdvcsOtYTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzZWxlY3QgaWQ9ImNvbW1lcmNlQ2F0YWxvZ0NhdGVnb3J5RmlsdGVyIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIiPlRvZGFzPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQGZvcmVhY2ggKCRjYXRhbG9nQ2F0ZWdvcmllc0NvbGxlY3Rpb24gYXMgJGNhdGVnb3J5KQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJ7eyAkY2F0ZWdvcnktPmlkIH19Ij57eyAkY2F0ZWdvcnktPm5hbWUgfX08L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAZW5kZm9yZWFjaAogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ZpZWxkIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPkVzdGF0dXM8L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c2VsZWN0IGlkPSJjb21tZXJjZUNhdGFsb2dTdGF0dXNGaWx0ZXIiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+VG9kb3M8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJkcmFmdCI+Qm9ycmFkb3I8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJhY3RpdmUiPkFjdGl2bzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9ImluYWN0aXZlIj5JbmFjdGl2bzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvbGFiZWw+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX3Byb2R1Y3RzIj4KICAgICAgICAgICAgICAgICAgICAgICAgQGZvcmVsc2UgKCRjYXRhbG9nUHJvZHVjdHNDb2xsZWN0aW9uIGFzICRwcm9kdWN0KQogICAgICAgICAgICAgICAgICAgICAgICAgICAgQHBocAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICRzZWFyY2hUZXh0ID0gbWJfc3RydG9sb3dlcihpbXBsb2RlKCcgJywgWwogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAkcHJvZHVjdC0+bmFtZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJHByb2R1Y3QtPnNrdSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJHByb2R1Y3QtPmJhcmNvZGUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICRwcm9kdWN0LT5jYXRlZ29yeT8tPm5hbWUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICRwcm9kdWN0LT5icmFuZD8tPm5hbWUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgXSksICdVVEYtOCcpOwogICAgICAgICAgICAgICAgICAgICAgICAgICAgQGVuZHBocAoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxhcnRpY2xlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX3Byb2R1Y3QiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1jYXRhbG9nLXByb2R1Y3QtY2FyZAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtc2VhcmNoPSJ7eyBlKCRzZWFyY2hUZXh0KSB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLWNhdGVnb3J5PSJ7eyAkcHJvZHVjdC0+Y2F0ZWdvcnlfaWQgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1zdGF0dXM9Int7ICRwcm9kdWN0LT5zdGF0dXMgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fcHJvZHVjdC1pbWFnZSI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBpZiAoJHByb2R1Y3QtPmltYWdlX3BhdGgpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aW1nIHNyYz0ie3sgYXNzZXQoJ3N0b3JhZ2UvJy4kcHJvZHVjdC0+aW1hZ2VfcGF0aCkgfX0iIGFsdD0ie3sgJHByb2R1Y3QtPm5hbWUgfX0iPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAZWxzZQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgSU1HCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBlbmRpZgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aDQ+e3sgJHByb2R1Y3QtPm5hbWUgfX08L2g0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIFNLVSB7eyAkcHJvZHVjdC0+c2t1IH19CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICDCtyB7eyAkcHJvZHVjdC0+Y2F0ZWdvcnk/LT5uYW1lID8/ICdTaW4gY2F0ZWdvcsOtYScgfX0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIMK3IHt7ICRwcm9kdWN0LT5icmFuZD8tPm5hbWUgPz8gJ1NpbiBtYXJjYScgfX0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9wPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX190YWdzIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX190YWciPnt7ICRwcm9kdWN0LT5pdGVtX3R5cGUgPT09ICdzZXJ2aWNlJyA/ICdTZXJ2aWNpbycgOiAnUHJvZHVjdG8nIH19PC9zcGFuPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX3RhZyI+e3sgJHByb2R1Y3QtPmlzX3Zpc2libGUgPyAnVmlzaWJsZScgOiAnT2N1bHRvJyB9fTwvc3Bhbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX190YWciPnt7IHVjZmlyc3QoJHByb2R1Y3QtPnN0YXR1cykgfX08L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19wcmljZSI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICR7eyBudW1iZXJfZm9ybWF0KChmbG9hdCkgKCRwcm9kdWN0LT5zYWxlX3ByaWNlID86ICRwcm9kdWN0LT5wcmljZSksIDIpIH19CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBpZiAoJHByb2R1Y3QtPnNhbGVfcHJpY2UpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c21hbGw+Tm9ybWFsOiAke3sgbnVtYmVyX2Zvcm1hdCgoZmxvYXQpICRwcm9kdWN0LT5wcmljZSwgMikgfX08L3NtYWxsPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAZW5kaWYKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fYWN0aW9ucyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHR5cGU9ImJ1dHRvbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNsYXNzPSJjb21tZXJjZS1jYXRhbG9nX19pY29uIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1jYXRhbG9nLWVkaXQtcHJvZHVjdAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS11cGRhdGUtYWN0aW9uPSJ7eyByb3V0ZSgnY29tZXJjaW8uY2F0YWxvZy5wcm9kdWN0cy51cGRhdGUnLCAkcHJvZHVjdCkgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLWl0ZW10eXBlPSJ7eyAkcHJvZHVjdC0+aXRlbV90eXBlIH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1uYW1lPSJ7eyAkcHJvZHVjdC0+bmFtZSB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtc2t1PSJ7eyAkcHJvZHVjdC0+c2t1IH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1iYXJjb2RlPSJ7eyAkcHJvZHVjdC0+YmFyY29kZSB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtY2F0ZWdvcnlpZD0ie3sgJHByb2R1Y3QtPmNhdGVnb3J5X2lkIH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1icmFuZGlkPSJ7eyAkcHJvZHVjdC0+YnJhbmRfaWQgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLXNob3J0ZGVzY3JpcHRpb249Int7ICRwcm9kdWN0LT5zaG9ydF9kZXNjcmlwdGlvbiB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtZGVzY3JpcHRpb249Int7ICRwcm9kdWN0LT5kZXNjcmlwdGlvbiB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtcHJpY2U9Int7ICRwcm9kdWN0LT5wcmljZSB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtc2FsZXByaWNlPSJ7eyAkcHJvZHVjdC0+c2FsZV9wcmljZSB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtdW5pdD0ie3sgJHByb2R1Y3QtPnVuaXQgfX0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLXN0YXR1cz0ie3sgJHByb2R1Y3QtPnN0YXR1cyB9fSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtdHJhY2tzdG9jaz0ie3sgJHByb2R1Y3QtPnRyYWNrX3N0b2NrID8gJzEnIDogJzAnIH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1pc3Zpc2libGU9Int7ICRwcm9kdWN0LT5pc192aXNpYmxlID8gJzEnIDogJzAnIH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYXJpYS1sYWJlbD0iRWRpdGFyIHByb2R1Y3RvIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3ZnIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIyIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMTIgMjBoOSI+PC9wYXRoPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xNi41IDMuNWEyLjEgMi4xIDAgMCAxIDMgM0w4IDE4bC00IDEgMS00IDExLjUtMTEuNVoiPjwvcGF0aD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvc3ZnPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2J1dHRvbj4KCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxmb3JtIG1ldGhvZD0iUE9TVCIgYWN0aW9uPSJ7eyByb3V0ZSgnY29tZXJjaW8uY2F0YWxvZy5wcm9kdWN0cy52aXNpYmlsaXR5JywgJHByb2R1Y3QpIH19Ij4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBjc3JmCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAbWV0aG9kKCdQQVRDSCcpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIHR5cGU9InN1Ym1pdCIgY2xhc3M9ImNvbW1lcmNlLWNhdGFsb2dfX2ljb24iIGFyaWEtbGFiZWw9IkNhbWJpYXIgdmlzaWJpbGlkYWQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzdmcgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2Utd2lkdGg9IjIiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMiAxMnM0LTcgMTAtNyAxMCA3IDEwIDctNCA3LTEwIDdTMiAxMiAyIDEyWiI+PC9wYXRoPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjEyIiByPSIzIj48L2NpcmNsZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3N2Zz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Zvcm0+CgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Zm9ybQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgbWV0aG9kPSJQT1NUIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWN0aW9uPSJ7eyByb3V0ZSgnY29tZXJjaW8uY2F0YWxvZy5wcm9kdWN0cy5kZXN0cm95JywgJHByb2R1Y3QpIH19IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb25zdWJtaXQ9InJldHVybiBjb25maXJtKCfCv1NlZ3VybyBxdWUgZGVzZWFzIGVsaW1pbmFyIGVzdGUgcHJvZHVjdG8/Jyk7IgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBAY3NyZgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQG1ldGhvZCgnREVMRVRFJykKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxidXR0b24gdHlwZT0ic3VibWl0IiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19faWNvbiIgYXJpYS1sYWJlbD0iRWxpbWluYXIgcHJvZHVjdG8iPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzdmcgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2Utd2lkdGg9IjIiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNNCA3aDE2Ij48L3BhdGg+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xMCAxMXY2Ij48L3BhdGg+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xNCAxMXY2Ij48L3BhdGg+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik02IDdsMSAxNGgxMGwxLTE0Ij48L3BhdGg+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik05IDdWNGg2djMiPjwvcGF0aD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3N2Zz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Zvcm0+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2FydGljbGU+CiAgICAgICAgICAgICAgICAgICAgICAgIEBlbXB0eQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29tbWVyY2UtY2F0YWxvZ19fZW1wdHkiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEHDum4gbm8gaGF5IHByb2R1Y3RvcyBvIHNlcnZpY2lvcyByZWdpc3RyYWRvcy4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICBAZW5kZm9yZWxzZQogICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPC9zZWN0aW9uPgogICAgICAgICAgICA8L3NlY3Rpb24+CiAgICAgICAgPC9kaXY+Cg==', true);

    if ($panel === false) {
        fail('No se pudo decodificar el panel Catalogos');
    }

    $dashboard = substr($dashboard, 0, $panelStart)
        .$panel."\n"
        .substr($dashboard, $panelStart);
}

if (! str_contains($dashboard, 'comercio-catalogos.css')) {
    $styleAnchor = <<<'BLADE'
    <link
        rel="stylesheet"
        href="{{ asset('assets/petpay-card/css/portals/comercio-branding.css') }}?v=20260711-04"
    >
BLADE;

    $styleInsert = $styleAnchor.<<<'BLADE'

    <link
        rel="stylesheet"
        href="{{ asset('assets/petpay-card/css/portals/comercio-catalogos.css') }}?v=20260712-01"
    >
BLADE;

    $dashboard = str_replace($styleAnchor, $styleInsert, $dashboard);
}

if (! str_contains($dashboard, 'comercio-catalogos.js')) {
    $scriptAnchor = <<<'BLADE'
    <script src="{{ asset('assets/petpay-card/js/portals/comercio-branding.js') }}?v=20260711-04"></script>
BLADE;

    $scriptInsert = $scriptAnchor.<<<'BLADE'

    <script src="{{ asset('assets/petpay-card/js/portals/comercio-catalogos.js') }}?v=20260712-01"></script>
BLADE;

    $dashboard = str_replace($scriptAnchor, $scriptInsert, $dashboard);
}

writeFileUtf8($dashboardPath, $dashboard);

echo "OK: Modulo Catalogos instalado.\n";